### ISSUE TITLE
Make more colorblind friendly, and avoid use of red-adjacent colors

### ISSUE THREAD

**Issue by jayrbolton** [jayrbolton/covid19-growth-dashboard#23]
Some colorblindness guidelines here: https://www.toptal.com/designers/colorfilter/

Avoid the red + black combo (technically it is orange, but close enough to red to warrant criticism)

**Comment by briehl** [comment]
Helpful website with a colorpicker https://davidmathlogic.com/colorblind/

**Comment by briehl** [comment]
PR: https://github.com/jayrbolton/covid19-growth-dashboard/pull/27
