### ISSUE TITLE
Disclaimers, attributions, sources

### ISSUE THREAD

**Issue by jayrbolton** [jayrbolton/covid19-growth-dashboard#9]
https://medium.com/nightingale/ten-considerations-before-you-create-another-chart-about-covid-19-27d3bd691be8
https://blog.datawrapper.de/coronaviruscharts/

**Comment by briehl** [comment]
Disclaimers should be copied both in the README of this repo, and in a page with a very clear link.

Maybe also link out to attributions, sources, the articles above, other articles, etc.

**Comment by jayrbolton** [comment]
I'll do this during lunch today.. this needs to get done so the site can be shared -- getting lots of requests from friends to share

**Comment by briehl** [comment]
I'll help out. I can help gather data, links to papers, write a little bit, etc.

Not sure what your coding plan is, but I can start adding to the readme.

**Comment by briehl** [comment]
Doesn't answer everything, but I updated the readme and added a contribution guide.

**Comment by jayrbolton** [comment]
I addressed this, at least partially, in pr #30 

I think it's good enough for now, and if there is any feedback in the future, we can incorporate it.
